feat: update KP to KMS and add a new test
terraform-ibm-modules/terraform-ibm-key-protect-key-ring pull request #394
Opened 2023-06-22 11:03 UTC by maheshwarishikha

### Description

Update the repository to use the term KMS instead of KP.
It includes changes in Readme, variable name/description, default example and adds a test for existing KMS.

### Types of changes in this PR

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

This repository now supports KMS including Key Protect and HPCS. Key protect term in the code has been renamed to KMS. Repository name is also changed to `terraform-ibm-kms-key-ring` from `terraform-ibm-key-protect-key-ring`.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-06-22 11:10 UTC, maheshwarishikha commented
/run pipeline

2023-06-22 14:15 UTC, shemau approved these changes
The code looks good.

There might be a naming issue/sequence issue. I think (not totally sure) that the .github/settings.xml is intended to change the name of the repo.
If/when the repo name changes, there are additional changes in the badges (README.md) and tests (go.mod) to reflect the new name.

There are NO changes to input variable names (variables.tf) or outputs; so I am not convinced this is major/breaking change. The module will get renamed, so there will be changes to all code consuming this module, but our current process deems these changes as non-breaking, since as far as I can tell there is no risk to deleting/recreating resources as a result of this change.

2023-06-23 09:24 UTC, maheshwarishikha commented
@shemau sure, converted to minor release. Thanks.

2023-06-23 09:44 UTC, ocofaigh commented on README.md
>  [![latest release](https://img.shields.io/github/v/release/terraform-ibm-modules/terraform-ibm-key-protect-key-ring?logo=GitHub&sort=semver)](https://github.com/terraform-ibm-modules/terraform-ibm-ke
`terraform-ibm-key-protect-key-ring` need to be updated in this badge url

2023-06-23 09:46 UTC, ocofaigh commented on README.md
>  For more information, about key management rings, see [creating key rings](https://cloud.ibm.com/docs/key-protect?topic=key-protect-grouping-keys#create-key-ring-api).
I think we need to explicitly mention Key Protect and HPCS are supported. the link here only points to key protect docs

2023-06-23 09:46 UTC, ocofaigh requested changes
some minor comments

2023-06-23 10:23 UTC, maheshwarishikha commented on README.md
>  [![latest release](https://img.shields.io/github/v/release/terraform-ibm-modules/terraform-ibm-key-protect-key-ring?logo=GitHub&sort=semver)](https://github.com/terraform-ibm-modules/terraform-ibm-ke
updated

2023-06-23 10:23 UTC, maheshwarishikha commented on README.md
>  For more information, about key management rings, see [creating key rings](https://cloud.ibm.com/docs/key-protect?topic=key-protect-grouping-keys#create-key-ring-api).
Made the required changes.

2023-06-23 10:23 UTC, maheshwarishikha commented
/run pipeline

2023-06-23 11:01 UTC, ocofaigh commented on README.md
> +This module creates a key ring to help organize keys in a KMS instance. KMS can be Key Protect and Hyper Protect Crypto Services(HPCS) instance.
change `and` -> `or` here:

> KMS can be Key Protect **or** Hyper Protect Crypto Services(HPCS) instance

2023-06-23 11:22 UTC, maheshwarishikha commented on README.md
> +This module creates a key ring to help organize keys in a KMS instance. KMS can be Key Protect and Hyper Protect Crypto Services(HPCS) instance.
updated

2023-06-23 11:24 UTC, maheshwarishikha commented
/run pipeline

2023-06-23 11:26 UTC, ocofaigh approved these changes

2023-06-23 11:37 UTC, merged

2023-06-23 11:38 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key-ring/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: